[[override]]
  name = "k8s.io/client-go"
  version = "v10.0.0"

[[override]]
  name = "k8s.io/kubernetes"
  version = "v1.13.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.0"

[prune]
  go-tests = true
  unused-packages = true
